### ISSUE TITLE
feat: support web for network image

### ISSUE THREAD

**Issue by hampsterx** [The-Artista/flutter_img#22]
```
Launching lib/web/main.dart on Chrome in debug mode...
../../.pub-cache/hosted/pub.dev/flutter_img-0.1.3/lib/src/network_image.dart:226:19: Error: The argument type 'File/*1*/' can't be assigned to the parameter type 'File/*2*/'.
 - 'File/*1*/' is from 'dart:io'.
 - 'File/*2*/' is from 'package:flutter_svg/src/utilities/_file_none.dart' ('../../.pub-cache/hosted/pub.dev/flutter_svg-2.0.7/lib/src/utilities/_file_none.dart').
        _imageFile!,
                  ^
```

**Comment by ishafiul** [comment]
hello, @hampsterx . Currently, this package only supports Android, IOS, and macOS, which is why it's not working with Chrome/Web. Thank you for informing me. I will fix this as soon as possible and update you.

**Comment by ishafiul** [comment]
hello @hampsterx, flutter_img got an update. please update the package. hope this will solve your issue for now. but remember there are lots of things to do to make this update perfect. hope I can do this very soon. thanks for reporting this issue. it will really help me to make this package perfect.
